### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by shaqqoor** [learn-co-curriculum/prototypal-oo-js-constructor-functions-readme#2]
function User(name, email) {
    this.name = name;   // [2] Set my context's property name to what
                      //     came in in the first argument (name)
    this.email = email; // [3] Set my context's property **name** to what
                      //     came in in the second argument (email)   _-> change name to email here_
}
 
// [1] Create a new "context", that's what `new` does
// Use _that_ new context inside of the execution of the `User` function
// also pass two parameters, "Lauren" and "lauren@example.com"
 
// [4]: Assign the new context thing with its this properties set to the
// variable `lauren`
let lauren = new User("Lauren", "lauren@example.com");
 
// [5]: Ask the new context for what's in its `.name` property
lauren.name //=> [6] "Lauren"****

**Comment by garettarrowood** [comment]
Resolved
